import "./globals.css";
import AOSInit from "@/components/AOS";

export const metadata = {
  title: "Yashik Yadav & Co",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/justlogo.ico" />
      </head>
      <body>
        <AOSInit /> {/* AOS initialized here */}
        {children}
      </body>
    </html>
  );
}
